Выполнил все лабораторные по крестиками-ноликам
demidko888/cppPractice pull request #7
Opened 2020-05-26 17:54 UTC by demidko888

2020-05-28 19:18 UTC, Toxin65 requested changes
Не соответствует ТЗ.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.h
> +
Многовато для заголовочного файла. Надо вынести в CPP файл.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.h
> +    class CellIdx {
Надо бы отделать сущности друг от друга, чтобы простынёй код не смотрелся.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.h
> +        }
Пишите в одну строку.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.h
> +        CellIdx(int x, int y) {
Пустой стоки не хватает. Обычно сначала методы, потом поля.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.h
> +            this->y = y;
В таких случаях this-> писать не надо. Вы в методе, т.е. внутри класса.
```suggestion
            x = iX;
            y = iY;
```
А перекрывающиеся идентификаторы -- это очень нехорошо.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.h
> +    bool operator==(const PlayField& second);
const забыли...

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	bool isNormal = abs(crossesCount - noughtsCount) < 2;
Типичная ошибка. Разность строго 0 или строго 1 в одну сторону, а не ХЗ как.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	bool isMovesEnd = getEmptyCells().empty();
А чего так дорого. Вы же уже посчитали нолики и крестики. Сделайте с ними условие.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	FieldStatus isWinOrDraw = isCrossesWin ? fsCrossesWin : isNoughtsWin ? fsNoughtsWin : fsDraw;
Нечитабельно.
И ниже тоже.
Не учтена потенциальная возможность одновременной победы обоих игроков в виду ошибки. Учесть, ассертнуть.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	return PlayField(*this) + index;
```suggestion
	return *this + index;
```
Зачем сразу копию делать? operator+ сделает вам копию сам.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	for (auto x : matrix)
Вот это вообще ни разу неинтуитивно... Выше ещё ничего, а тут...

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +}
Можно дешевле в общем. Ну да ладно.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	return crossCount > noughtCount ? csNought : csCross;
Не не не... Строго 0 или строго 1...
Ещё бы проверять что ни кто не победил ещё... И ассертнуть.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/TreeNode.cpp
> +	assert(children.size() <= DIM*DIM);
Не согласен. Строгий знак должен быть.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/TreeNode.h
> +using namespace std;
Такое писать в заголовочных файлах не надо!

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/TreeNode.h
> +    const PlayField state;
Этого поля быть не должно. Оно производное и источник потенциальных ошибок.

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/TreeNode.h
> +    const TreeNode* parent = nullptr;
const, а почему бы и нет...

2020-05-28 19:18 UTC, Toxin65 commented on TicTacToe/XOPlayer.h
> +    TreeNode* stepsTree;
Не соответствует ТЗ.

> - Определить для класса конструктор, принимающий на вход ссылку на построенное дерево решений (копии делать не надо, храним ссылку!)

2020-05-29 10:16 UTC, Toxin65 requested changes
Не соответствует ТЗ.

2020-05-29 10:16 UTC, Toxin65 commented on TicTacToe/XOPlayer.h
> +    TreeNode* stepsTree;
Не соответствует ТЗ. Ссылку от указателя отличать умеете?

2020-05-29 20:03 UTC, demidko888 commented on TicTacToe/XOPlayer.h
> +    TreeNode* stepsTree;
А сами крестики-нолики вы зачли, получается?

2020-05-30 15:52 UTC, Toxin65 commented on TicTacToe/XOPlayer.cpp
> +        for (int y = 0; y < 3; ++y) {
Что это? Откуда 3? Мы с вами не ругались разве по поводу magic value.
Исправляйте. Константы повторятся не должны. Ни какого дублирования.

2020-05-30 15:52 UTC, Toxin65 commented on TicTacToe/XOPlayer.h
> +    TreeNode* stepsTree;
Нет. Потому что поздно начали работать. Первая лаба сейчас не принимается. Пояснения есть в конференции в Телеге.

2020-05-30 15:57 UTC, Toxin65 requested changes
Посмотрел. И по-моему не исправлено ни одно замечание.
Исправляйте все замечания. Прямо все. Каждое.

2020-05-30 15:57 UTC, Toxin65 commented on TicTacToe/XOPlayer.h
> +    }
Я уже писал, но в другом месте, что это много для заголовка. Спрячьте в CPP. Зачем вы вообще это делали? Я же не писал тут замечаний.

2020-05-30 16:51 UTC, Toxin65 requested changes
Magic value, отступы, лишнее поле.

2020-05-30 16:51 UTC, Toxin65 commented on TicTacToe/PlayField.h
> +        int Y() const { return y; }
Не то я имел в виду. Друг от друга не надо отделять однородные элементы. Разнородные -- надо.

2020-05-30 16:51 UTC, Toxin65 commented on TicTacToe/TreeNode.cpp
> +	assert(children.size() < 9);
Ну ёмаё... Что такое 9? Magic value!

2020-05-30 16:51 UTC, Toxin65 commented on TicTacToe/XOPlayer.h
> +	TreeNode *currentTreeNode = nullptr;
Отступы поехали.
И выше тоже.

2020-05-30 16:51 UTC, Toxin65 commented on TicTacToe/XOPlayer.h
> +    PlayField currentFieldState;
Это поле лишнее.

2020-05-30 17:15 UTC, demidko888 commented on TicTacToe/XOPlayer.h
> +	TreeNode *currentTreeNode = nullptr;
Не понял вас. Нужно добавить отступы ?

2020-05-30 17:19 UTC, Toxin65 commented on TicTacToe/XOPlayer.h
> +	TreeNode *currentTreeNode = nullptr;
Если посмотреть внимательно, то отступы разные...

2020-05-30 17:28 UTC, demidko888 commented on TicTacToe/XOPlayer.h
> +	TreeNode *currentTreeNode = nullptr;
Странно, у меня в VS одинаковые

2020-05-30 17:30 UTC, demidko888 commented on TicTacToe/XOPlayer.h
> +	TreeNode *currentTreeNode = nullptr;
Поправил

2020-05-30 17:30 UTC, demidko888 commented on TicTacToe/XOPlayer.h
> +    PlayField currentFieldState;
Если вы про поле DIM, то я его использую для того, чтобы не было magic value в cpp файле

2020-05-30 17:35 UTC, Toxin65 commented on TicTacToe/XOPlayer.h
> +    PlayField currentFieldState;
Я про currentFieldState

2020-05-30 17:35 UTC, Toxin65 commented on TicTacToe/XOPlayer.h
> +	TreeNode *currentTreeNode = nullptr;
Возможно смешиваете пробелы и табуляции...

2020-05-30 17:37 UTC, demidko888 commented on TicTacToe/XOPlayer.h
> +	TreeNode *currentTreeNode = nullptr;
Хорошо, понял. Исправил в последнем коммите

2020-05-30 17:40 UTC, demidko888 commented on TicTacToe/XOPlayer.h
> +    PlayField currentFieldState;
Но у меня в cpp файле есть функции, которые используют данную переменную

2020-05-30 17:59 UTC, demidko888 commented on TicTacToe/XOPlayer.h
> +    PlayField currentFieldState;
И еще данная переменная нужна, чтобы отрисовывать поле в main.cpp

2020-05-30 20:52 UTC, demidko888 commented on TicTacToe/XOPlayer.h
> +    PlayField currentFieldState;
Удалил данную переменную в последнем коммите. Посмотрите, пожалуйста

2020-05-30 20:59 UTC, demidko888 commented on TicTacToe/XOPlayer.h
> +    PlayField currentFieldState;
Почистил код в последнем коммите

2020-05-31 19:31 UTC, Toxin65 requested changes
Исправить ВСЕ замечания.
Потом продолжим.

2020-05-31 19:31 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	return (isCrossesWin || isNoughtsWin || isMovesEnd) ? fsWin : fsNormal;
isMovesEnd излишне...

2020-05-31 19:31 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +			count++;
Можно было в одном цикле сделать...

2020-05-31 19:31 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	assert(count == 1 || count == 0);
Тут бы ещё сумму проверить. А то если ими уже всё поле заполнено -- то это фиаско, братан... )))

2020-05-31 20:10 UTC, demidko888 commented
Все исправил. Посмотрите, пожалуйста

2020-05-31 20:26 UTC, demidko888 commented on TicTacToe/PlayField.cpp
> +	assert(count == 1 || count == 0);
Добавил

2020-05-31 20:26 UTC, demidko888 commented on TicTacToe/PlayField.cpp
> +			count++;
Убрал

2020-05-31 20:26 UTC, demidko888 commented on TicTacToe/PlayField.cpp
> +	return (isCrossesWin || isNoughtsWin || isMovesEnd) ? fsWin : fsNormal;
Убрал

2020-06-01 08:24 UTC, Toxin65 requested changes
Косякнули немного.
Внимательно читайте, что от вас просят. Чтобы не ошибаться.

2020-06-01 08:24 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +		|| (matrix[2][0] == mark && matrix[1][1] == mark && matrix[0][2] == mark);
Так делать нехорошо. Опять magic value.
Я же написал в одном цикле сделать, а не похерить циклы...

2020-06-01 08:24 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	assert(count == 1 || count == 0);
Я бы csEmpty возвращял, а проверял бы значение там, где nextMove вызывается... Так логичнее. А то вызвали nextMove и упали.. (

2020-06-01 14:58 UTC, demidko888 commented
Немного не понял, что требуется изменить в методе GetNextMove(). Объясните, пожалуйста

2020-06-05 18:22 UTC, Toxin65 requested changes
Magic value.
Кое-что пропущено.
В остальном стало разительно лучше!

2020-06-05 18:22 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	bool isMovesEnd = crossesCount+noughtsCount==9;
9 -- magic value. Посчитайте от размера поля.

2020-06-05 18:31 UTC, demidko888 commented
Поправил

2020-06-05 19:08 UTC, Toxin65 requested changes
Поправить.

2020-06-05 19:08 UTC, Toxin65 commented on TicTacToe/main.cpp
> +        for (int i = 0; i < 9; i++) {
9 )))

2020-06-05 19:56 UTC, demidko888 commented on TicTacToe/main.cpp
> +        for (int i = 0; i < 9; i++) {
Исправил

2020-06-07 19:33 UTC, Toxin65 requested changes
Ну почти уже! С логикой косякнули.
Ладно. Принял. Вы это исправите, да и я уже проставил.

2020-06-07 19:33 UTC, Toxin65 commented on TicTacToe/main.cpp
> +        for (int i = 0; i < DIM*DIM; i++) {
Лучше, конечно, завести производный constexpr типа SIZE, ну да ладно.

2020-06-07 19:33 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	return (count == 1 ) ? csNought : (count==0)? csCross : csEmpty;
Подождите! csEmpty только если сумма = 9. При этом разность всё равно 0 или 1...

2020-06-08 08:41 UTC, demidko888 commented
Исправил!

2020-06-08 10:29 UTC, Toxin65 requested changes
А если бы немного головой подумать. То исправили бы правильно. А так получилось не очень.

2020-06-08 10:29 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +		return csEmpty;
**При этом разность всё равно 0 или 1...**
Читайте внимательно что я пишу!!! ВНИМАТЕЛЬНО!!!
Кроме того, своей головой тоже думайте, что пишите.
Ассертните на некорректную разность, а потом уж условия проверяйте.

2020-06-08 10:29 UTC, Toxin65 commented on TicTacToe/main.cpp
> +static constexpr int FIELD_SIZE = 9;
Ну что за глупости. DIM у вас был частью PlayField, и это правильно... Дак и FIELD_SIZE тоже должен быть частью PlayField.

2020-06-08 10:51 UTC, demidko888 commented on TicTacToe/PlayField.cpp
> +		return csEmpty;
Зачем? Я же ассертаю до этого в другом методе, который вызывает данный метод. Соответственно, зачем два раза ассертать? Если получится неправильное число, до этого метода даже не дойдёт, по идее...

2020-06-08 10:52 UTC, demidko888 commented on TicTacToe/main.cpp
> +static constexpr int FIELD_SIZE = 9;
Хорошо, исправлю на DIM

2020-06-08 11:04 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +		return csEmpty;
Вы не понимаете сути. Надо рассматривать метод как автономную единицу. Которая может быть вызвана в любом контексте.
Если разность некорретная -- он должен ассертить. А у вас он вернёт csEmpty просто если сумма 9 (кстати значение лучше написать через constexpr как и во втором вопросе). Либо вернёт csCross если разность отлична от 1 (т.е. если разность 0, -1, -2, -3, 2, 3...).

2020-06-08 11:05 UTC, Toxin65 commented on TicTacToe/main.cpp
> +static constexpr int FIELD_SIZE = 9;
Надеюсь вы правильно поняли, что я имел в виду.

2020-06-08 16:04 UTC, demidko888 commented
Вроде поправил. Посмотрите, пожалуйста

2020-06-08 16:09 UTC, Toxin65 commented on TicTacToe/PlayField.h
> +	static constexpr int DIM = 3;
```suggestion
	static constexpr int DIM = 3;
	static constexpr int SIZE = DIM*DIM;
```

2020-06-08 16:10 UTC, Toxin65 commented on TicTacToe/main.cpp
> +static constexpr int FIELD_DIM = PlayField::DIM;
Не нужно.

2020-06-08 16:10 UTC, Toxin65 commented on TicTacToe/main.cpp
> +        for (int i = 0; i < FIELD_DIM*FIELD_DIM; i++) {
```suggestion
        for (int i = 0; i < PlayField::SIZE; i++) {
```

2020-06-08 16:12 UTC, Toxin65 commented on TicTacToe/PlayField.cpp
> +	assert(count == 1 || count == 0);
```suggestion
	assert(crossCount + noughtCount <= SIZE);
	assert(count == 1 || count == 0);
	if (crossCount + noughtCount == SIZE)
		return csEmpty;
```

2020-06-08 16:23 UTC, demidko888 commented
Все поправил

2020-06-08 16:26 UTC, Toxin65 commented
Ага. Какой я молодец!

2020-06-08 16:28 UTC, demidko888 commented
Зато теперь не буду писать подобного!😁

2020-06-08 16:36 UTC, Toxin65 commented
>Зато теперь не буду писать подобного!grin
"- В плюсы больше ни ногой!"

2020-06-08 16:38 UTC, demidko888 commented
Они у меня уже прострелены

2020-06-30 10:01 UTC, merged